'use strict';

var fs  = require("fs");

/**
 * Sets path to SSH config file and returns corresponding callback to retrieve data with
 * @module configdata
 * @returns {module:configdata~configDataResult}
 */
module.exports = function () {
	var home_dir = process.env.HOME || process.env.HOMEPATH || process.env.USERPROFILE;
	var server_data_header = ["Server Name", "User", "Description", "Address", "Port"];
	var servers = [];
	var config_path = home_dir + '/.ssh/config';
	var customConfigFound = false;

	// Merge all files ~/.ssh/config-* into ~/.ssh/config
	let sshHomedir = home_dir + '/.ssh/';
	var files = fs.readdirSync(sshHomedir);
	var configContent = '# BEWARE: This file is automatically generated by ssg-js by combining all ~/.ssh/config-* files. Any manual changes in this file will be overwritten!';
	files.forEach(function (filename) {
		if (filename.indexOf('config-') !== 0) {
			return;
		}

		customConfigFound = true;
		configContent = configContent + "\n\n#" + filename + "\n\n" + fs.readFileSync(sshHomedir + filename);
	});

	if (customConfigFound) {
		fs.writeFileSync(config_path, configContent, function (err) {
			if (err) return console.log(err);
		});
	}

	// Read ~/.ssh/config
	var config = require('./configparse').getConfig(config_path);
	config.map(function(obj){
		if (obj.host.trim().indexOf('*') !== -1) {
			// skip
		} else if (obj.host.trim().indexOf(' ') !== -1) {
			var hosts = obj.host.split(' ');
			hosts.map(function (host) {
				var newObj = Object.assign(obj, {host: host});
				servers.push(JSON.parse(JSON.stringify(newObj)));
			});
		} else {
			servers.push(obj);
		}
	});

	var server_data = servers.map(function(obj){
		return [
			obj.host,
			("user" in obj) ? obj.user: "",
			("description" in obj) ? obj.description : "",
			("hostname" in obj) ? obj.hostname : "",
			("port" in obj) ? obj.port : "22",
		]
	});

	return {
		add_entries: function(entries) {
			server_data = server_data.concat(entries);
		},
		get_data: function(search_string) {
			var filtered_server_data = server_data.slice();
			filtered_server_data = filtered_server_data.filter(function(value){
				var return_val = false;
				for( var i = 0; i < 3; i++ ) {
					return_val = return_val || ( value[i].toLowerCase().indexOf(search_string.toLowerCase()) > -1 )
				}
				return return_val;
			});
			filtered_server_data.unshift(server_data_header);
			return filtered_server_data;
		}
	};

};

/**
 * @typedef {Object} module:configdata~configDataResult
 * @property {module:configdata~getDataCallback} get_data - Callback to retrieve filtered data
 */

/**
 * @callback module:configdata~getDataCallback
 * @param {String} [search_string=''] - Search term to filter data with
 * @returns {Array.<Array.<String>>}
 */
